version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb_app
    ports:
      - "27027:27017" # Puerto externo 27027 para que lo veas desde fuera
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3000:3000" # Backend ahora escucha en el 3000
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    environment:
      # El host 'db' es el nombre del servicio de arriba
      - MONGO_URI=mongodb://db:27017/reservas_db
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80" # Frontend ahora accesible en el 8080
    restart: always

volumes:
  mongo_data: